# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWa5tLrKDiNPb9cOIa_AmwiR7-69SIdJ
"""

app_py = r"""
import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input, decode_predictions
from tensorflow.keras.preprocessing import image
import numpy as np
import gradio as gr

print("TensorFlow:", tf.__version__)
print("GPU:", tf.config.list_physical_devices('GPU'))

model = MobileNetV2(weights='imagenet')
print("Model loaded.")

def classify_image(img):
    img = img.convert('RGB').resize((224,224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    preds = model.predict(x)
    decoded = decode_predictions(preds, top=3)[0]
    return {label: float(score) for (_, label, score) in decoded}

demo = gr.Interface(
    fn=classify_image,
    inputs=gr.Image(type="pil"),
    outputs=gr.Label(num_top_classes=3),
    title="Universal Image Recognition",
    description="Upload an image and get top-3 predictions (MobileNetV2)."
)

if __name__ == "__main__":
    demo.launch()
"""
with open("app.py","w") as f:
    f.write(app_py)
print("app.py created")