# -*- coding: utf-8 -*-
"""README.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5HsMxjwnJNxfh9pu4iaJL9iC0lFRiM1
"""

readme = """# Universal Image Recognition (MobileNetV2 + Gradio)

Upload any image (object, animal, landmark) and the model will return top-3 predictions.

## How to run
1. pip install -r requirements.txt
2. python app.py

## Files
- app.py : main Gradio app
- requirements.txt : dependencies
- README.md : this file

Author: Spoorti
"""
with open("README.md","w") as f:
    f.write(readme)
print("README.md created")

