# -*- coding: utf-8 -*-
"""requirements

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-zJ9L744KDg6_XP2uQBr6asyXJZ11Xw
"""

reqs = "tensorflow\ngradio\nnumpy\nPillow\n"
with open("requirements.txt","w") as f:
    f.write(reqs)
print("requirements.txt created")

